<Project Sdk="MSTest.Sdk/4.0.2">

	<PropertyGroup>
		<RootNamespace>DoenaSoft.PokerChips</RootNamespace>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseVSTest>true</UseVSTest>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\PokerChips_Windows\PokerChipsForWindows.csproj" />
	</ItemGroup>

</Project>
