<Project Sdk="MSTest.Sdk/4.0.2">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseVSTest>true</UseVSTest>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="..\PokerChips_Windows\Chip.cs" Link="Source\Chip.cs" />
		<Compile Include="..\PokerChips_Windows\ChipCalculator.cs" Link="Source\ChipCalculator.cs" />
	</ItemGroup>

</Project>
