<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net472</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<RootNamespace>DoenaSoft.PokerChips</RootNamespace>
		<AssemblyName>PokerChips</AssemblyName>
		<ApplicationIcon>DJDSOFT.ICO</ApplicationIcon>
		<LangVersion>latest</LangVersion>
		<AssemblyTitle>PokerChips for Windows</AssemblyTitle>
		<Description></Description>
		<Company>Doena Soft.</Company>
		<Product>PokerChips for Windows</Product>
		<Copyright>Copyright © Doena Soft.  2012 - 2026</Copyright>
		<AssemblyVersion>1.1</AssemblyVersion>
		<FileVersion>1.1</FileVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
		<ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="DJDSOFT.ICO" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\PokerChips_Library\PokerChips_Library.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Resource.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resource.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resource.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resource.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>
